
  Metrics/LineLength:
    Max: 500

  Metrics/BlockLength:
  #  ExcludedMethods: [‘describe’, ‘context’]
   Exclude:
     - ‘Rakefile’
     - ‘**/*.rake’
     - ‘test/**/*.rb’
     - 'config/environments/production.rb'
     - 'spec/controllers/posts_controller_spec.rb'
     - 'app/models/application_record.rb'
     - 'db/schema.rb'
     - 'spec/features/user_signs_up_spec.rb'


  Style/Documentation:
    Include:
     - app/models/**/*
     - lib/**/*

  Documentation:
    Enabled: false

  AllCops:
    Exclude: 
      - 'bin/setup'
      - 'bin/update'

