language: ruby
rvm:
- 2.5.0
services:
- postgresql
script:
- bundle install
- bin/rails db:drop
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: n1/ATDEpurcANYDvsvIKOVx0FQJxNVATDao5poj3Vd0BCf22UsB+tb2Jh/fqiyUFdSNp30RrABmJyGJ2V2Ds8cqgycJQgffhnmJSGNt/FLsks8ARrj3xfwBg1xYmrBrS0w1uJfzI3NiEIVV1asvWUgfMuNgs6EyxYHtmyNxcBBuqX3yCtl8jWd+aafPpB+qtUTLHWa8SuFTo9bBnWMHt788NaNb9T6V4ncwcaHfAYtXR/KUVzV8rITLJB9RsBzdrkMjSmIhyTKS9A4ITKh2IG92gRxRj0MmHo/vauo9ezJOFt4zdIZ9boX7NA7a9yHSsE5Uo7lZ7CU36CuERDYQLtnxde9Zk2A2K2cgZsoyWkuWPLL4lVBa0MqJ7/4D8PLlM+6zedoRAnzfe7DCsPTIZViYaEBxftA69f7TrrKUTohf5x5QCHUnujzT2FeXe6lWbboOlcg6+yFBBeGlPC0XoQO3qHMrX5rreNwuocz1AwDYQFgom5yRLKaok2lhWT16RUY74qZxTcocOHw2lP2Fw+lJ77oWOyeQEoEvwgcrTernKl8meSfHE4VzPPVYsWPQq3hAIWx7oygEsksWbrQl4ObyYzFqs+JoHic4Y/Zx0aaI9+eDfD6Ffg7DmdYewOrU7bX1SLKkHN3hswv/uY0J/R16z5fHZSoOfjCULWXjZSbs=
  app: good-guys
  on:
    repo: GuyCalloway/acebook-good-guys
run:
- rake db:migrate
- restart
