
# addons:
#  postgresql: 9.6
# #  code_climate:
# #      repo_token: <Get from Code Climate>
# after_success:
#  - bundle exec codeclimate-test-reporter
# before_script:
#   - cp config/database.yml.travis config/database.yml

# dist: trusty
# language: ruby
# rvm:
#  - 2.4.1
# script:
#  - bundle exec rails db:migrate RAILS_ENV=test
#  - bundle exec rspec
# services:
#  - postgresql



language: ruby
cache:
  - bundler
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate