language: ruby

deploy:
  provider: heroku
  api_key:
    secure: "kzP8As+O5G0aBJQ8Tcuhc7P9pebFFmgOwt4/zU2yAWdIAc3yZt6rw+/yBWrT3XPBtB1nfk2uizr+B/W+mibciHVoI2nqR/ADVsoJsB5w3tKd3Un8lhu4jLZQkqiT0Ghe/D/nCHOa3KVnSfsTNT6yQh7rG5pCOer+5+xReZX80kibsN7Fxve8r/U9kPHKAO4QdRCUdMHC2Z7g0nVfzcFvIQqOeWU1lY+0WOsO+LQprEf7Yh4zXsg0wnrdDIvTDxs92+e1MrvcOdrXjoH6GVopq3prPWMHlKU2xDzLRBnJ9YgXbW8sIyCbxGuXzP/SaZvUb2c1Tfslc2UNZcL6I2hemmU6peItcr0Ohuf9E9btgfPCy3JG8/Otw94/U5H0QYVUGoCU6dBZITLVobGGLuSwcKRdKyzriZlTYIVcwtEE1ooNiurtiClirk+yjbhZMfohs243mB1etvvYxcw4HpLgL0/jGFbZ68dOSZPa6MIxuVFKa5u0R35tiwsPovmw/txir1GJFJypUg2UbeMCxE4lU/gKacHw0AB12sRcluzYihU6i4QIr0xkIRvIWhl3qJsqagvLb4ZIvXkjV8v+tIWecx+w40yRcesJFkShZCkQ54ofxeqZijGDE2Y4MUIPTOfLJuLPl99B2OP1N07cviXSPQgzSSwfHX5B/E64nHWtFas="
  app: good-guys
  on:
    repo: GuyCalloway/acebook-good-guys